// Auto-generated by gulp-svg-sprites

@mixin svg($name, $pseudo: false, $display: inline-block) {
	@if($pseudo) {
		&:#{$pseudo} {
			@include svg-content($name, $display);
		}
	} @else {
		@include svg-content($name, $display);
	}
}

@mixin svg-content($name, $display: inline-block) {
	background-image: url('/_client/images/sprite.svg');
	background-repeat: no-repeat;
	content: ' ';
	display: $display;

	@if map-has-key($svgs, $name) {
		$svg: map-get($svgs, $name);

		background-position: map-get($svg, background-position);
		height: map-get($svg, height);
		width: map-get($svg, width);
	} @else {
		@warn "The SVG sprite `#{$name}` was not found.";
	}
}

@mixin svg-position($name) {
	@if map-has-key($svgs, $name) {
		$svg: map-get($svgs, $name);

		background-position: map-get($svg, background-position);
	} @else {
		@warn "The SVG sprite `#{$name}` was not found.";
	}
}

$svgs: (
{{#shapes}}
	{{name}}: (
		background-position: {{position.relative.xy}},
		width: {{width.outer}}px,
		height: {{height.outer}}px
	){{^last}},{{/last}}
{{/shapes}}
);
